apiVersion: v1
kind: Service
metadata:
  name: hss
  namespace: open5gs-4g
spec:
  selector:
    app: hss
  ports:
    - name: diameter-s6a
      protocol: TCP
      port: 3868
      targetPort: 3868
    - name: diameter-cx
      protocol: TCP
      port: 5868
      targetPort: 5868
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hss
  namespace: open5gs-4g
spec:
  selector:
    matchLabels:
      app: hss
  template:
    metadata:
      labels:
        app: hss
    spec:
      containers:
        - name: hss
          image: localhost:5000/open5gs-hss:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              value: mongodb://mongodb:27017/open5gs
          command: ["/opt/open5gs/bin/open5gs-hssd"]
          args: ["-c", "/opt/open5gs/etc/open5gs/hss.yaml"]
