apiVersion: v1
kind: Service
metadata:
  name: smf
  namespace: open5gs-4g
spec:
  selector:
    app: smf
  ports:
    - protocol: UDP
      port: 2123
      targetPort: 2123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
  namespace: open5gs-4g
spec:
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
        - name: smf
          image: localhost:5000/open5gs-pgwc:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              value: mongodb://mongodb:27017/open5gs
          command: ["/opt/open5gs/bin/open5gs-smfd"]
          args: ["-c", "/opt/open5gs/etc/open5gs/smf.yaml"]
