apiVersion: v1
kind: Service
metadata:
  name: upf
  namespace: open5gs-4g
spec:
  selector:
    app: upf
  ports:
    - name: s1u
      protocol: UDP
      port: 2152
      targetPort: 2152
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  namespace: open5gs-4g
spec:
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      initContainers:
        - name: init-tun
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["sh", "-c", "mkdir -p /dev/net && [ ! -c /dev/net/tun ] && mknod /dev/net/tun c 10 200 || true"]
      containers:
        - name: upf
          image: localhost:5000/open5gs-pgwu:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["/opt/open5gs/bin/open5gs-upfd"]
          args: ["-c", "/opt/open5gs/etc/open5gs/upf.yaml"]
