apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcrf-config
  namespace: open5gs
data:
  pcrf.conf: |
    Identity = "open5gs.localdomain";
    Realm = "localdomain";
    TLS_cred = "/opt/open5gs/etc/freeDiameter/ssl-cert-snakeoil.pem", "/opt/open5gs/etc/freeDiameter/ssl-cert-snakeoil.key";
    TLS_CA = "/opt/open5gs/etc/freeDiameter/ssl-cert-snakeoil.pem";

    LoadExtension = "dict_rfc5777.fdx";
    LoadExtension = "dict_mip6i.fdx";
    LoadExtension = "dict_nasreq.fdx";
    LoadExtension = "dict_nas_mipv6.fdx";
    LoadExtension = "dict_dcca.fdx";
    LoadExtension = "dict_dcca_3gpp.fdx";

    ConnectPeer = "open5gs.localdomain" { ConnectTo = "smf"; TcTimer = 60; TwTimer = 30; No_TLS; };
  pcrf.yaml: |
    logger:
      level: info
      file:
        path: /opt/open5gs/var/log/open5gs/pcrf.log
    db_uri: mongodb://mongodb:27017/open5gs
    pcrf:
      freeDiameter: /opt/open5gs/etc/open5gs/pcrf.conf
---
apiVersion: v1
kind: Service
metadata:
  name: pcrf
  namespace: open5gs
spec:
  selector:
    app: pcrf
  ports:
    - protocol: TCP
      port: 3868
      targetPort: 3868
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcrf
  namespace: open5gs
spec:
  selector:
    matchLabels:
      app: pcrf
  template:
    metadata:
      labels:
        app: pcrf
    spec:
      containers:
        - name: pcrf
          image: localhost:5000/open5gs-pcrf:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              value: mongodb://mongodb:27017/open5gs
          command: ["/opt/open5gs/bin/open5gs-pcrfd"]
          args: ["-c", "/opt/open5gs/etc/open5gs/pcrf.yaml"]
          volumeMounts:
            - name: pcrf-config
              mountPath: /opt/open5gs/etc/open5gs/pcrf.yaml
              subPath: pcrf.yaml
            - name: pcrf-config
              mountPath: /opt/open5gs/etc/open5gs/pcrf.conf
              subPath: pcrf.conf
            - name: certs
              mountPath: /opt/open5gs/etc/freeDiameter
      volumes:
        - name: pcrf-config
          configMap:
            name: open5gs-pcrf-config
        - name: certs
          configMap:
            name: open5gs-certs
