apiVersion: v1
kind: ConfigMap
metadata:
  name: srsran-config
  namespace: open5gs-4g
data:
  enb.conf: |
    [enb]
    enb_id = 0x19B
    mcc = 999
    mnc = 70
    mme_addr = mme.open5gs-4g.svc.cluster.local
    gtp_bind_addr = 0.0.0.0
    s1c_bind_addr = 0.0.0.0

    [enb_files]
    sib_config = /etc/srsran/sib.conf
    rb_config = /etc/srsran/rb.conf

    [rf]
    device_name = zeromq
    device_args = tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=23.04e6

  sib.conf: |
    sib1 = {
      p_max = 23;
      cell_id = 0x01;
      tac = 1;
      plmn_id_list = (
        {
          mcc = 999;
          mnc = 70;
          reser_for_operator_use = false;
        }
      );
      scheduling_info_list = (
        {
          si_periodicity = 16;
          si_mapping_info = (
            "sib3"
          );
        }
      );
      q_rx_lev_min = -130;
      si_window_length = 20;
      system_info_value_tag = 0;
    };

  rb.conf: |
    qci_config = (
      {
        qci = 9;
        user_plane_type = "tun";
        priority = 1;
        resource_type = "non_gbr";
        packet_err_rate = 0.001;
        packet_delay_budget = 100;
      }
    );

  ue.conf: |
    [ue]
    mode = sw

    [usim]
    imsi = 001010000000001
    key = 465B5CE8B199B49FAA5F0A2EE238A6BC
    opc = E8ED289DEBA952E4283B54E88E61883C

    [rf]
    device_name = zeromq
    device_args = tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srsran-4g
  namespace: open5gs-4g
spec:
  selector:
    matchLabels:
      app: srsran-4g
  template:
    metadata:
      labels:
        app: srsran-4g
    spec:
      containers:
        - name: enb
          image: wesamelsentresy/srsran:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["srsenb", "/etc/srsran/enb.conf"]
          volumeMounts:
            - name: config
              mountPath: /etc/srsran
        - name: ue
          image: wesamelsentresy/srsran:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["srsue", "/etc/srsran/ue.conf"]
          volumeMounts:
            - name: config
              mountPath: /etc/srsran
      volumes:
        - name: config
          configMap:
            name: srsran-config
