apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  namespace: open5gs
spec:
  selector:
    app: open5gs-webui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-webui
  namespace: open5gs
spec:
  selector:
    matchLabels:
      app: open5gs-webui
  template:
    metadata:
      labels:
        app: open5gs-webui
    spec:
      containers:
        - name: webui
          image: localhost:5000/open5gs-webui:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              value: mongodb://mongodb:27017/open5gs
          ports:
            - containerPort: 3000
