apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-certs
  namespace: open5gs
data:
  ssl-cert-snakeoil.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDZTCCAk2gAwIBAgIUfA2hVhK0N89qHK0C0Y2XqqxCGuQwDQYJKoZIhvcNAQEL
    BQAwHjEcMBoGA1UEAwwTb3BlbjVncy5sb2NhbGRvbWFpbjAeFw0yNTEyMjcwMDUz
    NTRaFw0yNjEyMjcwMDUzNTRaMB4xHDAaBgNVBAMME29wZW41Z3MubG9jYWxkb21h
    aW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDUb/SAJYdJfB+6Srk8
    ZtFd0iq2iVFhjlYAPtgM/WmyKHU/3EVtexsmiRhK3recnchLncrHbT6AdFseVJih
    AZQlZ1zp+FM3M+9ukayqt5pm5n6XP/LvfQX02Qped5NU2SDBzg069gn2IgifPMJb
    UMOXvxBcqVCVXA1oHl/pT849D6+u31s189Vqm4kEmOGaLd5xmbgFqqj9MajS0WRz
    hr2m+IdEltwv8XzsyrzFQVMCbfvHQGCqBzCvE4cwa8BQplBDercRkG+5DAkq21XB
    98Rx/CvRTdjbOWz3J2BwAd6X5pEwEqiyhBdse2kFEAV/rLBsLjLzM8BfwcrBR/al
    ELSxAgMBAAGjgZowgZcwCwYDVR0PBAQDAgQwMBMGA1UdJQQMMAoGCCsGAQUFBwMB
    MFQGA1UdEQRNMEuCD2hzcy5sb2NhbGRvbWFpboIPbW1lLmxvY2FsZG9tYWlugg0q
    LmxvY2FsZG9tYWluggtvcGVuNWdzLW1tZYILb3BlbjVncy1oc3MwHQYDVR0OBBYE
    FBbotUIo5PgahYeDKNDMZnn8wPBHMA0GCSqGSIb3DQEBCwUAA4IBAQBFY+pxfFCM
    6rg/bM3T/WbR3gduoiBw4dbq4RvL692pTlZqkYge2NBOHcABggTCT1h76mrq4ZQ0
    dkQa8U7sFIXfzWLAVtxCDONyZqU+4OC3BettibKBDV+udk6Xj99cyPqs9ujqd/9D
    gvhVf7NTdnO+LE9gXyZPApxr57h5MPJuJf6xJZ37NsZXp8xHh1UPqsa4+mYaF8//
    z0NlK3vvJTAYuDdL6DDp+9QslCbWBgZlStJj7MqQSQXKTvVNpuJAnoyVdyDKV0ms
    dNtPOWuySnzZ1g6Af4nYLCVQPKvv8xbE8Ga2pF2fUJH3/GniT68pR1aC+Qh4a0a9
    tOhYBS1H2Q7w
    -----END CERTIFICATE-----
  ssl-cert-snakeoil.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDUb/SAJYdJfB+6
    Srk8ZtFd0iq2iVFhjlYAPtgM/WmyKHU/3EVtexsmiRhK3recnchLncrHbT6AdFse
    VJihAZQlZ1zp+FM3M+9ukayqt5pm5n6XP/LvfQX02Qped5NU2SDBzg069gn2Igif
    PMJbUMOXvxBcqVCVXA1oHl/pT849D6+u31s189Vqm4kEmOGaLd5xmbgFqqj9MajS
    0WRzhr2m+IdEltwv8XzsyrzFQVMCbfvHQGCqBzCvE4cwa8BQplBDercRkG+5DAkq
    21XB98Rx/CvRTdjbOWz3J2BwAd6X5pEwEqiyhBdse2kFEAV/rLBsLjLzM8BfwcrB
    R/alELSxAgMBAAECggEAAN2iQjh5ee46W9yE6bnue4Ofrh/MWazQLtaK04G9E/d8
    nRynfRBjTJrntfhgd1WsZE7xk44kH6Kic3E3uygmHq85hm3WJ/7FRo+jJoHS+R3E
    JnR258gjt64Hsr0VBxL5+bFoXlJOeKEpDQUuZRk4hWkIBtRNRlCHR6G33F8V7WSV
    7ePHxSSl+atQQpzCJTyqfOMKeXiTCca0g2/oYUwdjjJG0b4CPGR5V0IvQv+IVjex
    vaBuFjALWfk3aKuM7iY+PB3uqnVPlzwa+ASMBDVqo6DhAV1L8mwr9cj4rfYI+GyA
    lAUu066XCZawcoETyJbctlIJ3zdRfD9gY7ZDlQVsaQKBgQD9yFT7k9YZNlzn8s4o
    si+0zIR72U8zUX2ezWdsiTriNx5itjdwRMxMp0zmY4cY3Q4wnuzgUmCdE6g24OCs
    s8LYHA5YvZ+dfz9JNejtgQVBr7ZF8OW7cGy4GzPQG6i22j1FkVDnSHlRBIshDVtL
    CZ9RKbGAZolfO1pBxwDFjMwxIwKBgQDWSyQU9MK7DDhUoH6eSTG2LchKzjNmu4WW
    mwIbHKIb0YTScGwId1nppZUfobexeZ7hiL7LuDnqfkMa0J+fmoJygfP16nU8P8Vi
    PO5Z5ciEvT6Lqdmd1xQGgKcaEuNlwb2KQuxfGmU5lcg6CzaSGRxJ8E69/Bsj9F0g
    ZMQeBLnCGwKBgQCimqRQ2UVZvCpE956+FoVYm53bWL5VTEZn5IX61eajoNtYNhZJ
    Wdto1d0A1Q5vkNuRrZJqnH2Ix1qFZwqtvTP/keJjW4QUvr5G40LOQlei4bmxEIux
    0HPodo15Lu+n0SdnFpe2yQnqLjYSxGMVLiIlN8iiU5B7MyU+dgp5iSAf7wKBgQC6
    FpBjvlSn96mnG6Q4shkAOeuXwk5ypN8R9NO0VX4UqDIuSEAYbgRfWFISIO4SqSmm
    cog1AmsQzcpaK9ah05v58g23fH2H71zpvT3CRT+GvYvl3n5CifYy21/Azaw4vjBp
    M0puH87NXdt9RCWEY1fkgVDvvFCZPWftbHO+GZ5yBwKBgD0a/m+u3TAi2KPw3YeS
    PESNFsCTvPSyzSHoB4QMS8aAFhF3z2yGwI9363II+/eKAcOigzOWpMpTAkC+gY8G
    TCTWrdoN9hTGLoEefOT2DtLY3im9Cb5NJyX+I565iGYvl+S/hhOmuz0QpEcimCgs
    PlhGWW61fzGlvJOnUrsKCtZR
    -----END PRIVATE KEY-----
