apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-certs
  namespace: open5gs
data:
  ssl-cert-snakeoil.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDHTCCAgWgAwIBAgIUR3xQT1+EeZJU6+MWfnWVTgvM/icwDQYJKoZIhvcNAQEL
    BQAwHjEcMBoGA1UEAwwTb3BlbjVncy5sb2NhbGRvbWFpbjAeFw0yNTEyMjUxNjI5
    MjVaFw0zNTEyMjMxNjI5MjVaMB4xHDAaBgNVBAMME29wZW41Z3MubG9jYWxkb21h
    aW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC+CyOhvYeXQoiZatiO
    7xRJ68AdstnwuVFtmAbuJhgm9fm8yWyDs9dSdkceZfvygy9ssdbIj5CCbTZSjcZd
    rP4D31RJbDr8Ai0LWgKXhfKUFQ1+aABB6Qv0EEia2x5UY+kk7Fh3Tizp2ATcVAo/
    HiJJzvmaTX/kI5h6htrXdKCDAxHR082f/V2GijNlzKuUMSQ+xLixCRKTLdkhHdfh
    bVtiSJS/LB9LQ+1FdID1DbWPA4JY4PYxykjG3ndM7a1B5kbRcy0RMblHO3Sn2aPZ
    sH6lpLgZIjW0R4U3Mryqzdovb+7f/ZYXrU00fJNCP+RIYtVLbtKIdnk0gQHtWXYB
    8ywlAgMBAAGjUzBRMB0GA1UdDgQWBBSJkzInKtZ4PIjWi1jIAb4utwJsvjAfBgNV
    HSMEGDAWgBSJkzInKtZ4PIjWi1jIAb4utwJsvjAPBgNVHRMBAf8EBTADAQH/MA0G
    CSqGSIb3DQEBCwUAA4IBAQA024xVfw4tqGdem8QdMS+iiGnZ+mhF35sEqWdR9/yN
    0neHvcDeZfttchTKEJXKFQElEnqPwehwkxfrbGpe1WQoi/VIOgzfM+h+PfPmfafJ
    yC+9OkK7sY3x+AjEesLYbH1mAthYF1r3kgv/LqHfaA5OyCOUr73Eszz+OEOByyCn
    Zm8dkZ2L0wU96JC0ncDuaRh+GGOkegozHWcSriImLYlMYhhZTeJZuk5zhS1d0NnB
    KPUF5mQBIpeJ/D7l7ydDVdJI8Pic9h0u7KhGpSJ5+Hz7VGrot1cfS6nD9NzCsrcD
    VgpzFSZsXIWiMt6vBeAMlwF1tMagWnB99nTxlGAmerCd
    -----END CERTIFICATE-----
  ssl-cert-snakeoil.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+CyOhvYeXQoiZ
    atiO7xRJ68AdstnwuVFtmAbuJhgm9fm8yWyDs9dSdkceZfvygy9ssdbIj5CCbTZS
    jcZdrP4D31RJbDr8Ai0LWgKXhfKUFQ1+aABB6Qv0EEia2x5UY+kk7Fh3Tizp2ATc
    VAo/HiJJzvmaTX/kI5h6htrXdKCDAxHR082f/V2GijNlzKuUMSQ+xLixCRKTLdkh
    HdfhbVtiSJS/LB9LQ+1FdID1DbWPA4JY4PYxykjG3ndM7a1B5kbRcy0RMblHO3Sn
    2aPZsH6lpLgZIjW0R4U3Mryqzdovb+7f/ZYXrU00fJNCP+RIYtVLbtKIdnk0gQHt
    WXYB8ywlAgMBAAECggEAKlFtrkr3ggGxTERkE7P+NxW1kodsi3Ogw8A6Ltaxwx87
    7MOHk+48kOLApG6+QzreGRyiwMdjPP/XvFtQpDRs3ezhpnXgzpQndqMk95u+sCXd
    +ttqz0J3RHJJ0J3ha5ZR6MRuUKbKToopTuyx2Ws65Gef4jHGvEUG46Xa3mZchb+K
    09MjOJPusgajeOXjymZQAfl3m2cldcewn23REkC9oPz8ButtEl+aJ9nvmU4SgcnW
    sud1ogmzCkcVU7vtit9yyY8LaNUM0IFWvKjAfBeBI3XHzAOrAMlZGBvfBoHI8vTo
    o+nSiiDpqvjV70ZgzlxHkDv0Q/5FbBh+y1VNkzM50wKBgQD4CW482KZLgCIkcdkv
    7sJ+9WYMa5HkaGAzEnaTP1V9er23Fgw+mKTlBl8CXR2Zd9v9MW8ri+tzhds1vyH/
    1RG2Mv+ViqA0jI9GfYbwh0gyPDnS7MrdWD4jkfNIFREjEqs7+JHKVOv+lbauc/1p
    1G67KvKJxJ4877FpPs6DVwWbzwKBgQDEJRJxE47C+zM0SCNKYg9k10AavqaAn/tL
    d80xq0Mi6TB9KdlVHn44IxXR5YGCpwu5l4AYs4wjbjdoIc+emwcKFHx3/vgTVhws
    YEYaTidWEb5ojtulpFACAchnZTpaLdkZOtxLQd2dYtTtz8WGXBzEELlAbLitwmwZ
    jHuwHPIxywKBgQDYWfmDL4LWRn0BhyDn835Jmaoa2VWXgweuZMNzKwJaAk8rPRsP
    GrxyXP1QpYIlFGyaTJ1owZJt4OtV1VNFwUfCwnc3rISTcauj0+h5M7dgwjG57vwA
    2HDTPAKV9HJPQoCEPgyFDVAQb+y5/MiloDu6HPsT+qIACx+X6sXdwHFO9wKBgAL4
    DK9pfF+3La886EvX8CO2nmHJQPvxb/xUc+askPeWUAWU/JUtQPvYjBwBPVSc8rB8
    epPlI9nlcTFCUcI01oZwiPHICjlAtGx3iJgdVrsWyasLfoejVRKytDXccmWrC/41
    xd/dv10CgfaXjoXaHxVYq3UuMB1xM/GvDrA7v+7BAoGBALAxu16gPBScjPrl0B6q
    EayGI7+8QSQr8I51moMINGpOFkx8ZTUokiv2OSe9XLRei6akF5A+aoGEQ3i5emYR
    wSmb2ye/jaFbNgo9nwot4vwjFyXP63nqwwC+xwFqU40VqpMgoNeLoT3mDaU8c8BP
    XSNG7VyerqHt8koaxiYvScNW
    -----END PRIVATE KEY-----
