apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-amf-config
  namespace: open5gs
data:
  amf.yaml: |
    logger:
      level: debug
    amf:
      amf_name: open5gs-amf0
      security:
        integrity_order: [ NIA2, NIA1, NIA0 ]
        ciphering_order: [ NEA0, NEA1, NEA2 ]
      network_name:
        full: Open5GS
        short: O5GS
      time:
        t3512:
          value: 540
        t3502:
          value: 720
      guami:
        - plmn_id:
            mcc: 999
            mnc: 70
          amf_id:
            region: 128
            set: 1
            pointer: 1
      tai:
        - plmn_id:
            mcc: 999
            mnc: 70
          tac: 1
      plmn_support:
        - plmn_id:
            mcc: 999
            mnc: 70
          s_nssai:
            - sst: 1
      ngap:
        server:
          - address: 0.0.0.0
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
          ausf:
            - uri: http://open5gs-ausf:7777
          udm:
            - uri: http://open5gs-udm:7777
          pcf:
            - uri: http://open5gs-pcf:7777
          discovery:
            delegated: no
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  namespace: open5gs
spec:
  selector:
    app: open5gs-amf
  ports:
    - name: ngap
      protocol: SCTP
      port: 38412
      targetPort: 38412
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-amf
  namespace: open5gs
spec:
  selector:
    matchLabels:
      app: open5gs-amf
  template:
    metadata:
      labels:
        app: open5gs-amf
    spec:
      containers:
        - name: amf
          image: localhost:5000/open5gs-amf:latest
          imagePullPolicy: IfNotPresent
          command: ["open5gs-amfd", "-c", "/opt/open5gs/etc/open5gs/amf.yaml"]
          volumeMounts:
            - name: amf-config
              mountPath: /opt/open5gs/etc/open5gs/amf.yaml
              subPath: amf.yaml
      volumes:
        - name: amf-config
          configMap:
            name: open5gs-amf-config
