apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  namespace: open5gs-5g
data:
  upf.yaml: |
    logger:
      file: /opt/open5gs/var/log/open5gs/upf.log
    upf:
      pfcp:
        - addr: 0.0.0.0
      gtpu:
        - addr: 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-upf
  namespace: open5gs-5g
spec:
  selector:
    app: open5gs-upf
  ports:
    - name: gtpu
      protocol: UDP
      port: 2152
      targetPort: 2152
    - name: pfcp
      protocol: UDP
      port: 8805
      targetPort: 8805
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-upf
  namespace: open5gs-5g
spec:
  selector:
    matchLabels:
      app: open5gs-upf
  template:
    metadata:
      labels:
        app: open5gs-upf
    spec:
      containers:
        - name: upf
          image: localhost:5000/open5gs-upf:latest
          volumeMounts:
            - name: upf-config
              mountPath: /opt/open5gs/etc/open5gs/upf.yaml
              subPath: upf.yaml
      volumes:
        - name: upf-config
          configMap:
            name: open5gs-upf-config
