apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs
data:
  smf.yaml: |
    db_uri: mongodb://mongodb:27017/open5gs
    logger:
      level: info
      file:
        path: /opt/open5gs/var/log/open5gs/smf.log
    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
      gtpc:
        server:
          - address: 0.0.0.0
      gtpu:
        server:
          - address: 0.0.0.0
      pfcp:
        server:
          - address: 0.0.0.0
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf
  namespace: open5gs
spec:
  selector:
    app: open5gs-smf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
    - name: gtpc
      protocol: UDP
      port: 2123
      targetPort: 2123
    - name: pfcp
      protocol: UDP
      port: 8805
      targetPort: 8805
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-smf
  namespace: open5gs
spec:
  selector:
    matchLabels:
      app: open5gs-smf
  template:
    metadata:
      labels:
        app: open5gs-smf
    spec:
      containers:
        - name: smf
          image: localhost:5000/open5gs-smf:latest
          imagePullPolicy: IfNotPresent
          command: ["/opt/open5gs/bin/open5gs-smfd"]
          args: ["-c", "/opt/open5gs/etc/open5gs/smf.yaml"]
          volumeMounts:
            - name: smf-config
              mountPath: /opt/open5gs/etc/open5gs/smf.yaml
              subPath: smf.yaml
      volumes:
        - name: smf-config
          configMap:
            name: open5gs-smf-config
