apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: open5gs-5g
data:
  smf.yaml: |
    logger:
      file: /opt/open5gs/var/log/open5gs/smf.log
    smf:
      freeDiameter:
        identity: smf.localdomain
        realm: localdomain
        listen_on: 0.0.0.0
      pfcp:
        - addr: 0.0.0.0
      gtpc:
        - addr: 0.0.0.0
      gtpu:
        - addr: 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf
  namespace: open5gs-5g
spec:
  selector:
    app: open5gs-smf
  ports:
    - protocol: UDP
      port: 2123
      targetPort: 2123
    - protocol: UDP
      port: 8805
      targetPort: 8805
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-smf
  namespace: open5gs-5g
spec:
  selector:
    matchLabels:
      app: open5gs-smf
  template:
    metadata:
      labels:
        app: open5gs-smf
    spec:
      containers:
        - name: smf
          image: localhost:5000/open5gs-smf:latest
          volumeMounts:
            - name: smf-config
              mountPath: /opt/open5gs/etc/open5gs/smf.yaml
              subPath: smf.yaml
      volumes:
        - name: smf-config
          configMap:
            name: open5gs-smf-config
