apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-config
  namespace: open5gs
data:
  nrf.yaml: |
    logger:
      level: info
    db_uri: mongodb://mongodb.open5gs.svc.cluster.local/open5gs
    nrf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf
  namespace: open5gs
spec:
  selector:
    app: open5gs-nrf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nrf
  namespace: open5gs
spec:
  selector:
    matchLabels:
      app: open5gs-nrf
  template:
    metadata:
      labels:
        app: open5gs-nrf
    spec:
      containers:
        - name: nrf
          image: localhost:5000/open5gs-nrf:latest
          imagePullPolicy: IfNotPresent
          command: ["open5gs-nrfd", "-c", "/opt/open5gs/etc/open5gs/nrf.yaml"]
          volumeMounts:
            - name: nrf-config
              mountPath: /opt/open5gs/etc/open5gs/nrf.yaml
              subPath: nrf.yaml
      volumes:
        - name: nrf-config
          configMap:
            name: open5gs-nrf-config
