apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-config
  namespace: open5gs-5g
data:
  nrf.yaml: |
    logger:
      file: /opt/open5gs/var/log/open5gs/nrf.log
    nrf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf
  namespace: open5gs-5g
spec:
  selector:
    app: open5gs-nrf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nrf
  namespace: open5gs-5g
spec:
  selector:
    matchLabels:
      app: open5gs-nrf
  template:
    metadata:
      labels:
        app: open5gs-nrf
    spec:
      containers:
        - name: nrf
          image: localhost:5000/open5gs-nrf:latest
          volumeMounts:
            - name: nrf-config
              mountPath: /opt/open5gs/etc/open5gs/nrf.yaml
              subPath: nrf.yaml
      volumes:
        - name: nrf-config
          configMap:
            name: open5gs-nrf-config
