apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  namespace: open5gs
data:
  udm.yaml: |
    logger:
      level: info
    udm:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
          discovery:
            delegated: no
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-udm
  namespace: open5gs
spec:
  selector:
    app: open5gs-udm
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-udm
  namespace: open5gs
spec:
  selector:
    matchLabels:
      app: open5gs-udm
  template:
    metadata:
      labels:
        app: open5gs-udm
    spec:
      containers:
        - name: udm
          image: localhost:5000/open5gs-udm:latest
          imagePullPolicy: IfNotPresent
          command: ["open5gs-udmd", "-c", "/opt/open5gs/etc/open5gs/udm.yaml"]
          volumeMounts:
            - name: udm-config
              mountPath: /opt/open5gs/etc/open5gs/udm.yaml
              subPath: udm.yaml
      volumes:
        - name: udm-config
          configMap:
            name: open5gs-udm-config
