apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  namespace: open5gs
data:
  udr.yaml: |
    db_uri: mongodb://mongodb:27017/open5gs
    logger:
      level: info
      file:
        path: /opt/open5gs/var/log/open5gs/udr.log
    udr:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
          discovery:
            delegated: no
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-udr
  namespace: open5gs
spec:
  selector:
    app: open5gs-udr
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-udr
  namespace: open5gs
spec:
  selector:
    matchLabels:
      app: open5gs-udr
  template:
    metadata:
      labels:
        app: open5gs-udr
    spec:
      containers:
        - name: udr
          image: localhost:5000/open5gs-udr:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              value: mongodb://mongodb:27017/open5gs
          command: ["open5gs-udrd", "-c", "/opt/open5gs/etc/open5gs/udr.yaml"]
          volumeMounts:
            - name: udr-config
              # FIX: when using subPath, mountPath must be the full file path
              mountPath: /opt/open5gs/etc/open5gs/udr.yaml
              subPath: udr.yaml
      volumes:
        - name: udr-config
          configMap:
            name: open5gs-udr-config
