apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  namespace: open5gs-5g
data:
  udr.yaml: |
    logger:
      file: /opt/open5gs/var/log/open5gs/udr.log
    udr:
      sbi:
        - addr: 0.0.0.0
          port: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-udr
  namespace: open5gs-5g
spec:
  selector:
    app: open5gs-udr
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-udr
  namespace: open5gs-5g
spec:
  selector:
    matchLabels:
      app: open5gs-udr
  template:
    metadata:
      labels:
        app: open5gs-udr
    spec:
      containers:
        - name: udr
          image: localhost:5000/open5gs-udr:latest
          volumeMounts:
            - name: udr-config
              mountPath: /opt/open5gs/etc/open5gs/udr.yaml
              subPath: udr.yaml
      volumes:
        - name: udr-config
          configMap:
            name: open5gs-udr-config
