apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  namespace: open5gs-5g
data:
  ausf.yaml: |
    logger:
      file: /opt/open5gs/var/log/open5gs/ausf.log
    ausf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-ausf
  namespace: open5gs-5g
spec:
  selector:
    app: open5gs-ausf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-ausf
  namespace: open5gs-5g
spec:
  selector:
    matchLabels:
      app: open5gs-ausf
  template:
    metadata:
      labels:
        app: open5gs-ausf
    spec:
      containers:
        - name: ausf
          image: localhost:5000/open5gs-ausf:latest
          volumeMounts:
            - name: ausf-config
              mountPath: /opt/open5gs/etc/open5gs/ausf.yaml
              subPath: ausf.yaml
      volumes:
        - name: ausf-config
          configMap:
            name: open5gs-ausf-config
