apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: open5gs
data:
  nssf.yaml: |
    logger:
      level: info
    nssf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
          discovery:
            delegated: no
          nsi:
            - s_nssai:
                sst: 1
              uri: http://open5gs-nrf:7777
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-nssf
  namespace: open5gs
spec:
  selector:
    app: open5gs-nssf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nssf
  namespace: open5gs
spec:
  selector:
    matchLabels:
      app: open5gs-nssf
  template:
    metadata:
      labels:
        app: open5gs-nssf
    spec:
      containers:
        - name: nssf
          image: localhost:5000/open5gs-nssf:latest
          imagePullPolicy: IfNotPresent
          command: ["open5gs-nssfd", "-c", "/opt/open5gs/etc/open5gs/nssf.yaml"]
          volumeMounts:
            - name: nssf-config
              mountPath: /opt/open5gs/etc/open5gs/nssf.yaml
              subPath: nssf.yaml
      volumes:
        - name: nssf-config
          configMap:
            name: open5gs-nssf-config
