apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: open5gs-5g
data:
  nssf.yaml: |
    logger:
      file: /opt/open5gs/var/log/open5gs/nssf.log
    nssf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-nssf
  namespace: open5gs-5g
spec:
  selector:
    app: open5gs-nssf
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-nssf
  namespace: open5gs-5g
spec:
  selector:
    matchLabels:
      app: open5gs-nssf
  template:
    metadata:
      labels:
        app: open5gs-nssf
    spec:
      containers:
        - name: nssf
          image: localhost:5000/open5gs-nssf:latest
          volumeMounts:
            - name: nssf-config
              mountPath: /opt/open5gs/etc/open5gs/nssf.yaml
              subPath: nssf.yaml
      volumes:
        - name: nssf-config
          configMap:
            name: open5gs-nssf-config
