apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  namespace: open5gs
data:
  pcf.yaml: |
    db_uri: mongodb://mongodb:27017/open5gs
    logger:
      level: debug
      file:
        path: /opt/open5gs/var/log/open5gs/pcf.log
    pcf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
            advertise:
              - open5gs-pcf
        client:
          nrf:
            - uri: http://open5gs-nrf:7777
          discovery:
            delegated: no
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcf
  namespace: open5gs
spec:
  selector:
    app: open5gs-pcf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-pcf
  namespace: open5gs
spec:
  selector:
    matchLabels:
      app: open5gs-pcf
  template:
    metadata:
      labels:
        app: open5gs-pcf
    spec:
      containers:
        - name: pcf
          image: localhost:5000/open5gs-pcf:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URI
              value: mongodb://mongodb:27017/open5gs
          command: ["open5gs-pcfd", "-c", "/opt/open5gs/etc/open5gs/pcf.yaml"]
          volumeMounts:
            - name: pcf-config
              mountPath: /opt/open5gs/etc/open5gs/pcf.yaml
              subPath: pcf.yaml
      volumes:
        - name: pcf-config
          configMap:
            name: open5gs-pcf-config
